
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidateEmailSoap", targetNamespace = "http://www.webservicex.net")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateEmailSoap {


    /**
     * This method returns true or false for a given email address
     * 
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsValidEmail", action = "http://www.webservicex.net/IsValidEmail")
    @WebResult(name = "IsValidEmailResult", targetNamespace = "http://www.webservicex.net")
    @RequestWrapper(localName = "IsValidEmail", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.IsValidEmail")
    @ResponseWrapper(localName = "IsValidEmailResponse", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.IsValidEmailResponse")
    public boolean isValidEmail(
        @WebParam(name = "Email", targetNamespace = "http://www.webservicex.net")
        String email);

}
